name: slack test

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: notify
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
